/** Components uploaded in the latest friend commit on feat/revive. */
export const NEW_COMPONENT_SLUGS = new Set([
  "bookshelf",
  "accessible-action",
  "accordionos",
  "card-folder",
  "confidential-folder",
  "corner-video",
  "focus-testimonials",
  "infinite-grid",
  "polaroid-drag",
  "pop-tilt-cards",
  "rolling-card-stack",
  "scroll-stack-deck",
  "stack-scroll-reveal",
  "perspective-text-scroll",
  "wheel-carousel",
  "editorial-deck",
  "client-card",
  "coverflow-drag",
  "create-menu",
  "liquid-index",
  "photo-albums",
  "slide-subscribe",
  "set-timer",
  "stacked-outline-text",
  "drawer-buttons",
  "prompt-box",
  "get-in-touch",
  "theme-toggle",
  "scan-document",
  "polaroid-stack",
  "analog-stick",
  "paper-shred-button",
  "holographic-referral-card",
  "curve-drawer",
  "overlapping-slider",
  "tactile-button",
  "gooey-navbar",
  "dynamic-grid-gallery",
  "scroll-split-cards",
]);

export function isNewComponent(slug: string) {
  return NEW_COMPONENT_SLUGS.has(slug);
}
